// Mocks generated by Mockito 5.4.6 from annotations
// in hydration_tracker/test/reminder_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:hydration_tracker/models/cup_size.dart' as _i8;
import 'package:hydration_tracker/models/reminder.dart' as _i7;
import 'package:hydration_tracker/models/streak.dart' as _i9;
import 'package:hydration_tracker/models/user.dart' as _i5;
import 'package:hydration_tracker/models/water_intake.dart' as _i6;
import 'package:hydration_tracker/services/database_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> insertUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #insertUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [id],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> updateUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertWaterIntake(_i6.WaterIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWaterIntake,
          [intake],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.WaterIntake>> getWaterIntakeForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaterIntakeForDate,
          [date],
        ),
        returnValue:
            _i4.Future<List<_i6.WaterIntake>>.value(<_i6.WaterIntake>[]),
      ) as _i4.Future<List<_i6.WaterIntake>>);

  @override
  _i4.Future<List<_i6.WaterIntake>> getWaterIntakeForDateAndUser(
    DateTime? date,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaterIntakeForDateAndUser,
          [
            date,
            userId,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.WaterIntake>>.value(<_i6.WaterIntake>[]),
      ) as _i4.Future<List<_i6.WaterIntake>>);

  @override
  _i4.Future<List<_i6.WaterIntake>> getWaterIntakeForWeek(
    String? userId,
    DateTime? startDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaterIntakeForWeek,
          [
            userId,
            startDate,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.WaterIntake>>.value(<_i6.WaterIntake>[]),
      ) as _i4.Future<List<_i6.WaterIntake>>);

  @override
  _i4.Future<void> insertDailyWaterGoal(_i6.DailyWaterGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDailyWaterGoal,
          [goal],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i6.DailyWaterGoal?> getDailyWaterGoal(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyWaterGoal,
          [
            userId,
            date,
          ],
        ),
        returnValue: _i4.Future<_i6.DailyWaterGoal?>.value(),
      ) as _i4.Future<_i6.DailyWaterGoal?>);

  @override
  _i4.Future<void> insertReminder(_i7.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertReminder,
          [reminder],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Reminder>> getReminders(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReminders,
          [userId],
        ),
        returnValue: _i4.Future<List<_i7.Reminder>>.value(<_i7.Reminder>[]),
      ) as _i4.Future<List<_i7.Reminder>>);

  @override
  _i4.Future<void> updateReminder(_i7.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReminder,
          [reminder],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteReminder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReminder,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.CupSize>> getCupSizes() => (super.noSuchMethod(
        Invocation.method(
          #getCupSizes,
          [],
        ),
        returnValue: _i4.Future<List<_i8.CupSize>>.value(<_i8.CupSize>[]),
      ) as _i4.Future<List<_i8.CupSize>>);

  @override
  _i4.Future<void> insertCupSize(_i8.CupSize? cupSize) => (super.noSuchMethod(
        Invocation.method(
          #insertCupSize,
          [cupSize],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertStreak(_i9.Streak? streak) => (super.noSuchMethod(
        Invocation.method(
          #insertStreak,
          [streak],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i9.Streak?> getStreak(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getStreak,
          [userId],
        ),
        returnValue: _i4.Future<_i9.Streak?>.value(),
      ) as _i4.Future<_i9.Streak?>);

  @override
  _i4.Future<void> updateStreak(_i9.Streak? streak) => (super.noSuchMethod(
        Invocation.method(
          #updateStreak,
          [streak],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<double> getTotalIntakeForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalIntakeForDate,
          [date],
        ),
        returnValue: _i4.Future<double>.value(0.0),
      ) as _i4.Future<double>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> setCurrentUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentUserId,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clearCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #clearCurrentUserId,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i4.Future<_i5.User?>.value(),
      ) as _i4.Future<_i5.User?>);

  @override
  _i4.Future<void> createUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.WaterIntake>> getAllWaterIntakes() => (super.noSuchMethod(
        Invocation.method(
          #getAllWaterIntakes,
          [],
        ),
        returnValue:
            _i4.Future<List<_i6.WaterIntake>>.value(<_i6.WaterIntake>[]),
      ) as _i4.Future<List<_i6.WaterIntake>>);

  @override
  _i4.Future<List<_i6.WaterIntake>> getAllWaterIntakesForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllWaterIntakesForUser,
          [userId],
        ),
        returnValue:
            _i4.Future<List<_i6.WaterIntake>>.value(<_i6.WaterIntake>[]),
      ) as _i4.Future<List<_i6.WaterIntake>>);

  @override
  _i4.Future<void> addWaterIntake(_i6.WaterIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWaterIntake,
          [intake],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateWaterIntake(_i6.WaterIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWaterIntake,
          [intake],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteWaterIntake(String? intakeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWaterIntake,
          [intakeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Reminder>> getAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #getAllReminders,
          [],
        ),
        returnValue: _i4.Future<List<_i7.Reminder>>.value(<_i7.Reminder>[]),
      ) as _i4.Future<List<_i7.Reminder>>);

  @override
  _i4.Future<void> addReminder(_i7.Reminder? reminder) => (super.noSuchMethod(
        Invocation.method(
          #addReminder,
          [reminder],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.CupSize>> getAllCupSizes() => (super.noSuchMethod(
        Invocation.method(
          #getAllCupSizes,
          [],
        ),
        returnValue: _i4.Future<List<_i8.CupSize>>.value(<_i8.CupSize>[]),
      ) as _i4.Future<List<_i8.CupSize>>);

  @override
  _i4.Future<void> addCupSize(_i8.CupSize? cupSize) => (super.noSuchMethod(
        Invocation.method(
          #addCupSize,
          [cupSize],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateCupSize(_i8.CupSize? cupSize) => (super.noSuchMethod(
        Invocation.method(
          #updateCupSize,
          [cupSize],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCupSize(String? cupSizeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCupSize,
          [cupSizeId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Streak>> getAllStreaks() => (super.noSuchMethod(
        Invocation.method(
          #getAllStreaks,
          [],
        ),
        returnValue: _i4.Future<List<_i9.Streak>>.value(<_i9.Streak>[]),
      ) as _i4.Future<List<_i9.Streak>>);

  @override
  _i4.Future<void> addStreak(_i9.Streak? streak) => (super.noSuchMethod(
        Invocation.method(
          #addStreak,
          [streak],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteStreak(String? streakId) => (super.noSuchMethod(
        Invocation.method(
          #deleteStreak,
          [streakId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
