// Mocks generated by Mockito 5.4.6 from annotations
// in hydration_tracker/test/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:flutter/material.dart' as _i13;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i14;
import 'package:hydration_tracker/models/challenge.dart' as _i19;
import 'package:hydration_tracker/models/cup_size.dart' as _i10;
import 'package:hydration_tracker/models/friend.dart' as _i18;
import 'package:hydration_tracker/models/leaderboard.dart' as _i20;
import 'package:hydration_tracker/models/reminder.dart' as _i9;
import 'package:hydration_tracker/models/streak.dart' as _i11;
import 'package:hydration_tracker/models/user.dart' as _i7;
import 'package:hydration_tracker/models/water_intake.dart' as _i8;
import 'package:hydration_tracker/services/database_service.dart' as _i5;
import 'package:hydration_tracker/services/firebase_service.dart' as _i17;
import 'package:hydration_tracker/services/notification_service.dart' as _i12;
import 'package:hydration_tracker/services/weather_service.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseFirestore_2 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFirebaseAuth_3 extends _i1.SmartFake implements _i4.FirebaseAuth {
  _FakeFirebaseAuth_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_4 extends _i1.SmartFake
    implements _i4.UserCredential {
  _FakeUserCredential_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i5.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i6.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i6.Future<_i2.Database>);

  @override
  _i6.Future<void> insertUser(_i7.User? user) => (super.noSuchMethod(
        Invocation.method(
          #insertUser,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.User?> getUser(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [id],
        ),
        returnValue: _i6.Future<_i7.User?>.value(),
      ) as _i6.Future<_i7.User?>);

  @override
  _i6.Future<void> updateUser(_i7.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertWaterIntake(_i8.WaterIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertWaterIntake,
          [intake],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.WaterIntake>> getWaterIntakeForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaterIntakeForDate,
          [date],
        ),
        returnValue:
            _i6.Future<List<_i8.WaterIntake>>.value(<_i8.WaterIntake>[]),
      ) as _i6.Future<List<_i8.WaterIntake>>);

  @override
  _i6.Future<List<_i8.WaterIntake>> getWaterIntakeForDateAndUser(
    DateTime? date,
    String? userId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaterIntakeForDateAndUser,
          [
            date,
            userId,
          ],
        ),
        returnValue:
            _i6.Future<List<_i8.WaterIntake>>.value(<_i8.WaterIntake>[]),
      ) as _i6.Future<List<_i8.WaterIntake>>);

  @override
  _i6.Future<List<_i8.WaterIntake>> getWaterIntakeForWeek(
    String? userId,
    DateTime? startDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWaterIntakeForWeek,
          [
            userId,
            startDate,
          ],
        ),
        returnValue:
            _i6.Future<List<_i8.WaterIntake>>.value(<_i8.WaterIntake>[]),
      ) as _i6.Future<List<_i8.WaterIntake>>);

  @override
  _i6.Future<void> insertDailyWaterGoal(_i8.DailyWaterGoal? goal) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDailyWaterGoal,
          [goal],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i8.DailyWaterGoal?> getDailyWaterGoal(
    String? userId,
    DateTime? date,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyWaterGoal,
          [
            userId,
            date,
          ],
        ),
        returnValue: _i6.Future<_i8.DailyWaterGoal?>.value(),
      ) as _i6.Future<_i8.DailyWaterGoal?>);

  @override
  _i6.Future<void> insertReminder(_i9.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertReminder,
          [reminder],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.Reminder>> getReminders(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReminders,
          [userId],
        ),
        returnValue: _i6.Future<List<_i9.Reminder>>.value(<_i9.Reminder>[]),
      ) as _i6.Future<List<_i9.Reminder>>);

  @override
  _i6.Future<void> updateReminder(_i9.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReminder,
          [reminder],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteReminder(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReminder,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.CupSize>> getCupSizes() => (super.noSuchMethod(
        Invocation.method(
          #getCupSizes,
          [],
        ),
        returnValue: _i6.Future<List<_i10.CupSize>>.value(<_i10.CupSize>[]),
      ) as _i6.Future<List<_i10.CupSize>>);

  @override
  _i6.Future<void> insertCupSize(_i10.CupSize? cupSize) => (super.noSuchMethod(
        Invocation.method(
          #insertCupSize,
          [cupSize],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> insertStreak(_i11.Streak? streak) => (super.noSuchMethod(
        Invocation.method(
          #insertStreak,
          [streak],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i11.Streak?> getStreak(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getStreak,
          [userId],
        ),
        returnValue: _i6.Future<_i11.Streak?>.value(),
      ) as _i6.Future<_i11.Streak?>);

  @override
  _i6.Future<void> updateStreak(_i11.Streak? streak) => (super.noSuchMethod(
        Invocation.method(
          #updateStreak,
          [streak],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<double> getTotalIntakeForDate(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTotalIntakeForDate,
          [date],
        ),
        returnValue: _i6.Future<double>.value(0.0),
      ) as _i6.Future<double>);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserId,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> setCurrentUserId(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #setCurrentUserId,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearCurrentUserId() => (super.noSuchMethod(
        Invocation.method(
          #clearCurrentUserId,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i6.Future<_i7.User?>.value(),
      ) as _i6.Future<_i7.User?>);

  @override
  _i6.Future<void> createUser(_i7.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i8.WaterIntake>> getAllWaterIntakes() => (super.noSuchMethod(
        Invocation.method(
          #getAllWaterIntakes,
          [],
        ),
        returnValue:
            _i6.Future<List<_i8.WaterIntake>>.value(<_i8.WaterIntake>[]),
      ) as _i6.Future<List<_i8.WaterIntake>>);

  @override
  _i6.Future<List<_i8.WaterIntake>> getAllWaterIntakesForUser(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllWaterIntakesForUser,
          [userId],
        ),
        returnValue:
            _i6.Future<List<_i8.WaterIntake>>.value(<_i8.WaterIntake>[]),
      ) as _i6.Future<List<_i8.WaterIntake>>);

  @override
  _i6.Future<void> addWaterIntake(_i8.WaterIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWaterIntake,
          [intake],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateWaterIntake(_i8.WaterIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWaterIntake,
          [intake],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteWaterIntake(String? intakeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteWaterIntake,
          [intakeId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i9.Reminder>> getAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #getAllReminders,
          [],
        ),
        returnValue: _i6.Future<List<_i9.Reminder>>.value(<_i9.Reminder>[]),
      ) as _i6.Future<List<_i9.Reminder>>);

  @override
  _i6.Future<void> addReminder(_i9.Reminder? reminder) => (super.noSuchMethod(
        Invocation.method(
          #addReminder,
          [reminder],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i10.CupSize>> getAllCupSizes() => (super.noSuchMethod(
        Invocation.method(
          #getAllCupSizes,
          [],
        ),
        returnValue: _i6.Future<List<_i10.CupSize>>.value(<_i10.CupSize>[]),
      ) as _i6.Future<List<_i10.CupSize>>);

  @override
  _i6.Future<void> addCupSize(_i10.CupSize? cupSize) => (super.noSuchMethod(
        Invocation.method(
          #addCupSize,
          [cupSize],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateCupSize(_i10.CupSize? cupSize) => (super.noSuchMethod(
        Invocation.method(
          #updateCupSize,
          [cupSize],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteCupSize(String? cupSizeId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCupSize,
          [cupSizeId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i11.Streak>> getAllStreaks() => (super.noSuchMethod(
        Invocation.method(
          #getAllStreaks,
          [],
        ),
        returnValue: _i6.Future<List<_i11.Streak>>.value(<_i11.Streak>[]),
      ) as _i6.Future<List<_i11.Streak>>);

  @override
  _i6.Future<void> addStreak(_i11.Streak? streak) => (super.noSuchMethod(
        Invocation.method(
          #addStreak,
          [streak],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteStreak(String? streakId) => (super.noSuchMethod(
        Invocation.method(
          #deleteStreak,
          [streakId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i12.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> recordNotificationDismissal() => (super.noSuchMethod(
        Invocation.method(
          #recordNotificationDismissal,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> recordNotificationResponse() => (super.noSuchMethod(
        Invocation.method(
          #recordNotificationResponse,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> scheduleReminder(_i9.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleReminder,
          [reminder],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelReminder(_i9.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelReminder,
          [reminder],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> cancelAllReminders() => (super.noSuchMethod(
        Invocation.method(
          #cancelAllReminders,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> showImmediateNotification({
    required String? title,
    required String? body,
    String? payload,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showImmediateNotification,
          [],
          {
            #title: title,
            #body: body,
            #payload: payload,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> scheduleGoalReminder({
    required String? userId,
    required double? remainingAmount,
    required _i13.TimeOfDay? time,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleGoalReminder,
          [],
          {
            #userId: userId,
            #remainingAmount: remainingAmount,
            #time: time,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> scheduleStreakReminder({
    required String? userId,
    required int? currentStreak,
    required _i13.TimeOfDay? time,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleStreakReminder,
          [],
          {
            #userId: userId,
            #currentStreak: currentStreak,
            #time: time,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i14.PendingNotificationRequest>> getPendingNotifications() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingNotifications,
          [],
        ),
        returnValue: _i6.Future<List<_i14.PendingNotificationRequest>>.value(
            <_i14.PendingNotificationRequest>[]),
      ) as _i6.Future<List<_i14.PendingNotificationRequest>>);

  @override
  _i6.Future<void> cancelNotification(int? id) => (super.noSuchMethod(
        Invocation.method(
          #cancelNotification,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> debugPrintPendingNotifications() => (super.noSuchMethod(
        Invocation.method(
          #debugPrintPendingNotifications,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> debugTestIntervalScheduling(_i9.Reminder? reminder) =>
      (super.noSuchMethod(
        Invocation.method(
          #debugTestIntervalScheduling,
          [reminder],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [WeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherService extends _i1.Mock implements _i15.WeatherService {
  MockWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i15.WeatherData> get weatherStream => (super.noSuchMethod(
        Invocation.getter(#weatherStream),
        returnValue: _i6.Stream<_i15.WeatherData>.empty(),
      ) as _i6.Stream<_i15.WeatherData>);

  @override
  _i6.Future<_i15.WeatherData?> getCurrentWeather() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [],
        ),
        returnValue: _i6.Future<_i15.WeatherData?>.value(),
      ) as _i6.Future<_i15.WeatherData?>);

  @override
  void startBackgroundUpdates(
          {Duration? interval = const Duration(minutes: 30)}) =>
      super.noSuchMethod(
        Invocation.method(
          #startBackgroundUpdates,
          [],
          {#interval: interval},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void stopBackgroundUpdates() => super.noSuchMethod(
        Invocation.method(
          #stopBackgroundUpdates,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i15.WeatherData?> forceRefresh() => (super.noSuchMethod(
        Invocation.method(
          #forceRefresh,
          [],
        ),
        returnValue: _i6.Future<_i15.WeatherData?>.value(),
      ) as _i6.Future<_i15.WeatherData?>);

  @override
  _i6.Future<_i15.WeatherData?> getWeatherWithAutoRefresh() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherWithAutoRefresh,
          [],
        ),
        returnValue: _i6.Future<_i15.WeatherData?>.value(),
      ) as _i6.Future<_i15.WeatherData?>);

  @override
  double calculateWeatherAdjustment(_i15.WeatherData? weather) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateWeatherAdjustment,
          [weather],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  _i6.Future<String?> getLocationName(
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocationName,
          [
            latitude,
            longitude,
          ],
        ),
        returnValue: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  bool isWeatherDataRecent(_i15.WeatherData? weather) => (super.noSuchMethod(
        Invocation.method(
          #isWeatherDataRecent,
          [weather],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<DateTime?> getLastUpdateTime() => (super.noSuchMethod(
        Invocation.method(
          #getLastUpdateTime,
          [],
        ),
        returnValue: _i6.Future<DateTime?>.value(),
      ) as _i6.Future<DateTime?>);

  @override
  _i6.Future<Duration> getUpdateFrequency() => (super.noSuchMethod(
        Invocation.method(
          #getUpdateFrequency,
          [],
        ),
        returnValue: _i6.Future<Duration>.value(_FakeDuration_1(
          this,
          Invocation.method(
            #getUpdateFrequency,
            [],
          ),
        )),
      ) as _i6.Future<Duration>);

  @override
  _i6.Future<void> setUpdateFrequency(Duration? frequency) =>
      (super.noSuchMethod(
        Invocation.method(
          #setUpdateFrequency,
          [frequency],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getWeatherHydrationTip(_i15.WeatherData? weather) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherHydrationTip,
          [weather],
        ),
        returnValue: _i16.dummyValue<String>(
          this,
          Invocation.method(
            #getWeatherHydrationTip,
            [weather],
          ),
        ),
      ) as String);
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i17.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Stream<_i4.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i4.User?>.empty(),
      ) as _i6.Stream<_i4.User?>);

  @override
  _i3.FirebaseFirestore get firestore => (super.noSuchMethod(
        Invocation.getter(#firestore),
        returnValue: _FakeFirebaseFirestore_2(
          this,
          Invocation.getter(#firestore),
        ),
      ) as _i3.FirebaseFirestore);

  @override
  _i4.FirebaseAuth get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeFirebaseAuth_3(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i4.FirebaseAuth);

  @override
  _i6.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserCredential> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #signInWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<_i4.UserCredential> createUserWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUserWithEmailAndPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #createUserWithEmailAndPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetPassword(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i4.UserCredential> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i6.Future<_i4.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i6.Future<_i4.UserCredential>);

  @override
  _i6.Future<void> createOrUpdateUser(_i7.User? user) => (super.noSuchMethod(
        Invocation.method(
          #createOrUpdateUser,
          [user],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i7.User?> getUser(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [userId],
        ),
        returnValue: _i6.Future<_i7.User?>.value(),
      ) as _i6.Future<_i7.User?>);

  @override
  _i6.Future<List<_i7.User>> searchUsers(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchUsers,
          [query],
        ),
        returnValue: _i6.Future<List<_i7.User>>.value(<_i7.User>[]),
      ) as _i6.Future<List<_i7.User>>);

  @override
  _i6.Future<void> sendFriendRequest({
    required String? fromUserId,
    required String? fromUserName,
    required String? toUserId,
    String? message,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendFriendRequest,
          [],
          {
            #fromUserId: fromUserId,
            #fromUserName: fromUserName,
            #toUserId: toUserId,
            #message: message,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i18.FriendRequest>> getPendingFriendRequests(
          String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPendingFriendRequests,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i18.FriendRequest>>.empty(),
      ) as _i6.Stream<List<_i18.FriendRequest>>);

  @override
  _i6.Future<void> acceptFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptFriendRequest,
          [requestId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> declineFriendRequest(String? requestId) =>
      (super.noSuchMethod(
        Invocation.method(
          #declineFriendRequest,
          [requestId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Stream<List<_i18.Friend>> getUserFriends(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserFriends,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i18.Friend>>.empty(),
      ) as _i6.Stream<List<_i18.Friend>>);

  @override
  _i6.Future<_i19.Challenge?> createChallenge({
    required String? title,
    required String? description,
    required _i19.ChallengeType? type,
    required DateTime? startDate,
    required DateTime? endDate,
    required Map<String, dynamic>? rules,
    required List<String>? participants,
    required String? createdBy,
    required String? createdByName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createChallenge,
          [],
          {
            #title: title,
            #description: description,
            #type: type,
            #startDate: startDate,
            #endDate: endDate,
            #rules: rules,
            #participants: participants,
            #createdBy: createdBy,
            #createdByName: createdByName,
          },
        ),
        returnValue: _i6.Future<_i19.Challenge?>.value(),
      ) as _i6.Future<_i19.Challenge?>);

  @override
  _i6.Stream<List<_i19.Challenge>> getUserChallenges(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserChallenges,
          [userId],
        ),
        returnValue: _i6.Stream<List<_i19.Challenge>>.empty(),
      ) as _i6.Stream<List<_i19.Challenge>>);

  @override
  _i6.Stream<List<_i19.ChallengeParticipant>> getChallengeParticipants(
          String? challengeId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChallengeParticipants,
          [challengeId],
        ),
        returnValue: _i6.Stream<List<_i19.ChallengeParticipant>>.empty(),
      ) as _i6.Stream<List<_i19.ChallengeParticipant>>);

  @override
  _i6.Stream<_i20.Leaderboard?> getGlobalLeaderboard({
    _i20.LeaderboardPeriod? period = _i20.LeaderboardPeriod.weekly,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGlobalLeaderboard,
          [],
          {
            #period: period,
            #limit: limit,
          },
        ),
        returnValue: _i6.Stream<_i20.Leaderboard?>.empty(),
      ) as _i6.Stream<_i20.Leaderboard?>);

  @override
  _i6.Stream<_i20.Leaderboard?> getStreakLeaderboard({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStreakLeaderboard,
          [],
          {#limit: limit},
        ),
        returnValue: _i6.Stream<_i20.Leaderboard?>.empty(),
      ) as _i6.Stream<_i20.Leaderboard?>);

  @override
  _i6.Future<void> updateUserScore({
    required String? userId,
    required double? score,
    required Map<String, dynamic>? stats,
    _i20.LeaderboardType? type = _i20.LeaderboardType.global,
    _i20.LeaderboardPeriod? period = _i20.LeaderboardPeriod.weekly,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserScore,
          [],
          {
            #userId: userId,
            #score: score,
            #stats: stats,
            #type: type,
            #period: period,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> logEvent(
    String? name, [
    Map<String, Object>? parameters,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #logEvent,
          [
            name,
            parameters,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
