// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6jQP_xEpNqt3HQfb9RzUv3mhLh8LxGWs',
    appId: '1:285299670930:web:647f1bafce8453b1560b4b',
    messagingSenderId: '285299670930',
    projectId: 'hydration-tracker-app-2024',
    authDomain: 'hydration-tracker-app-2024.firebaseapp.com',
    storageBucket: 'hydration-tracker-app-2024.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB768jjWb9Y0D7A_ftxQQyqWz7GMKI0UNE',
    appId: '1:285299670930:android:ebfa9119e6f9131e560b4b',
    messagingSenderId: '285299670930',
    projectId: 'hydration-tracker-app-2024',
    storageBucket: 'hydration-tracker-app-2024.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1RUwW-zLvLJD8NZCcWgJ20y3_kVPOL_s',
    appId: '1:285299670930:ios:9fdbb91a1c2e1f9a560b4b',
    messagingSenderId: '285299670930',
    projectId: 'hydration-tracker-app-2024',
    storageBucket: 'hydration-tracker-app-2024.firebasestorage.app',
    iosBundleId: 'com.example.hydrationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1RUwW-zLvLJD8NZCcWgJ20y3_kVPOL_s',
    appId: '1:285299670930:ios:9fdbb91a1c2e1f9a560b4b',
    messagingSenderId: '285299670930',
    projectId: 'hydration-tracker-app-2024',
    storageBucket: 'hydration-tracker-app-2024.firebasestorage.app',
    iosBundleId: 'com.example.hydrationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6jQP_xEpNqt3HQfb9RzUv3mhLh8LxGWs',
    appId: '1:285299670930:web:2b96a3352acf8ab8560b4b',
    messagingSenderId: '285299670930',
    projectId: 'hydration-tracker-app-2024',
    authDomain: 'hydration-tracker-app-2024.firebaseapp.com',
    storageBucket: 'hydration-tracker-app-2024.firebasestorage.app',
  );
}
